sonar.projectKey=Armotik_fog_rml
sonar.organization=armotik

sonar.sources=src/fog_rml
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.10
sonar.qualitygate.wait=true

sonar.coverage.exclusions=src/fog_rml/__main__.py, src/fog_rml/commands/**
