sonar.projectKey=Armotik_pyhartig
sonar.organization=armotik

sonar.sources=src/pyhartig
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml

sonar.coverage.exclusions=src/pyhartig/__main__.py, src/pyhartig/commands/**